// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU7mFrMbCx3KT3aJmCrMAvKmYm6JgL_G8',
    appId: '1:936955635480:web:9e72de52b52eabf786e06d',
    messagingSenderId: '936955635480',
    projectId: 'agenpets',
    authDomain: 'agenpets.firebaseapp.com',
    storageBucket: 'agenpets.firebasestorage.app',
    measurementId: 'G-07D8MQ3W98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd4yk9yjyEIA1vVlBuFyDMmfyY_-ti96k',
    appId: '1:936955635480:android:dad2a038ccd3cf2286e06d',
    messagingSenderId: '936955635480',
    projectId: 'agenpets',
    storageBucket: 'agenpets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkwmO_-HkDmIa_dHroQxKfIrykFBWsGnI',
    appId: '1:936955635480:ios:d95f4eec064132f086e06d',
    messagingSenderId: '936955635480',
    projectId: 'agenpets',
    storageBucket: 'agenpets.firebasestorage.app',
    iosBundleId: 'com.example.agenpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkwmO_-HkDmIa_dHroQxKfIrykFBWsGnI',
    appId: '1:936955635480:ios:d95f4eec064132f086e06d',
    messagingSenderId: '936955635480',
    projectId: 'agenpets',
    storageBucket: 'agenpets.firebasestorage.app',
    iosBundleId: 'com.example.agenpet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU7mFrMbCx3KT3aJmCrMAvKmYm6JgL_G8',
    appId: '1:936955635480:web:7a322dbd6089a94886e06d',
    messagingSenderId: '936955635480',
    projectId: 'agenpets',
    authDomain: 'agenpets.firebaseapp.com',
    storageBucket: 'agenpets.firebasestorage.app',
    measurementId: 'G-41EWSN4S5G',
  );
}
